repos:
  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: bun prettier --write --log-level warn
        language: system
        types_or: [ts, tsx]

      - id: eslint
        name: ESLint
        entry: bun eslint --fix --cache
        language: system
        types_or: [ts, tsx]

