/**
 * @fileoverview A one-time bootstrap credential, not a peer.
 *
 * A {@link PeerInviteRecord} exists to answer one question — "how do two people who already
 * want to talk actually exchange enough information to become peers?" — and to stop existing
 * the moment it has answered it. It never appears in `AppConfig.peers`: the invariant that
 * file already documents ("no request from an unlisted origin is served... discovery must
 * never be the thing that creates a peer") applies here unchanged. An invite only ever
 * *proposes* a peer relationship; only an explicit accept, verified against this record,
 * ever writes one.
 *
 * The redeem secret itself is never a field here. `secretHash` is a sha256 of it — the
 * record on disk is useless to whoever can merely read the file, the same reasoning that
 * keeps a peer's own token out of `AppConfig` entirely.
 */

import type { PeerTier } from "./peer";

export interface PeerInviteRecord {
  /** 128 bits of randomness, hex-encoded. Unguessable on purpose: see {@link isInviteId}. */
  readonly id: string;
  /**
   * The name the inviter will file the redeemer under, once accepted. Purely the inviter's
   * own bookkeeping — it is what shows up in their `jazz peers list` and `jazz peers log`
   * afterward, and has no bearing on what the redeemer chooses to call the inviter.
   */
  readonly inviteeName: string;
  /**
   * What the inviter wants to be called by whoever redeems this — shown in the accept
   * confirmation ("This invite is from ...") and used as the redeemer's default local name
   * for them. Defaults to the inviter's hostname if they don't pick one; nothing here needs
   * to match any name the inviter uses for themselves elsewhere.
   */
  readonly inviterDisplayName: string;
  /** The inviter's own `/peer/ask` URL, handed to whoever redeems this. */
  readonly inviterAskUrl: string;
  /** What the redeemer will be allowed to learn, once accepted. */
  readonly proposedTier: PeerTier;
  readonly createdAt: string;
  readonly expiresAt: string;
  /** sha256(secret), hex-encoded. The secret itself is never persisted. */
  readonly secretHash: string;
  /** Set the instant redemption succeeds. Absence is what makes an invite still usable. */
  readonly redeemedAt?: string;
  /** The name the redeemer chose to file the inviter under. Recorded for audit only. */
  readonly redeemedAs?: string;
  /** Set when the inviter cancels the link before anyone redeems it. */
  readonly revokedAt?: string;
}

/** 32 lowercase hex characters: 128 bits, generated by `randomBytes(16)`. */
const INVITE_ID_PATTERN = /^[0-9a-f]{32}$/;

/**
 * Whether a string is shaped like an invite id.
 *
 * Checked before any lookup touches the filesystem, the same discipline `FileRunStore` uses
 * for run ids — an id that never came from `randomBytes` did not come from this system, and
 * must not be allowed to steer a path join.
 */
export function isInviteId(value: string): boolean {
  return INVITE_ID_PATTERN.test(value);
}

export type PeerInviteStatus = "active" | "expired" | "redeemed" | "revoked";

/** What `list`/`accept` actually care about, derived rather than stored. */
export function inviteStatus(record: PeerInviteRecord, now: Date): PeerInviteStatus {
  if (record.revokedAt !== undefined) return "revoked";
  if (record.redeemedAt !== undefined) return "redeemed";
  if (new Date(record.expiresAt).getTime() <= now.getTime()) return "expired";
  return "active";
}

/**
 * Redeeming an invite fails in one of these specific ways, each shown to the human verbatim
 * rather than collapsed into "invalid invite" — the same reasoning the ledger uses for
 * distinguishing `refused` from `expired`: the failure itself is the useful information.
 */
export type RedeemInviteOutcome =
  | { readonly kind: "ok"; readonly record: PeerInviteRecord }
  | { readonly kind: "not-found" }
  | { readonly kind: "expired"; readonly expiresAt: string }
  | { readonly kind: "revoked" }
  | { readonly kind: "already-redeemed" }
  | { readonly kind: "bad-secret" };
